export const BOOK_RECOMMENDATIONS_REQUEST = 'BOOK_RECOMMENDATIONS_REQUEST';
export const BOOK_RECOMMENDATIONS_SUCCESS = 'BOOK_RECOMMENDATIONS_SUCCESS';
export const BOOK_RECOMMENDATIONS_FAIL = 'BOOK_RECOMMENDATIONS_FAIL';

export const CLEAR_BOOK_RECOMMENDATIONS = 'CLEAR_BOOK_RECOMMENDATIONS';

