export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST'
export const STORE_LIST_SUCCSESS = 'STORE_LIST_SUCCSESS'
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL'


export const STORE_DETAILS_REQUEST = 'STORE_DETAILS_REQUEST'
export const STORE_DETAILS_SUCCESS = 'STORE_DETAILS_SUCCESS'
export const STORE_DETAILS_FAIL = 'STORE_DETAILS_FAIL'

export const STORE_BY_USER_REQUEST = 'STORE_BY_USER_REQUEST'
export const STORE_BY_USER_SUCCESS = 'STORE_BY_USER_SUCCESS'
export const STORE_BY_USER_FAIL = 'STORE_BY_USER_FAIL'
